### ISSUE TITLE
Opening subpages in tabs works - sometimes

### ISSUE THREAD

**Issue by stefan-schilling** [robisim74/angular-l10n#341] opened 2023-04-04 16:15 UTC
**Describe the bug**
Using version 14.0.0 with Angular 14.

Being our main page /dashboard (or here: /en/dashboard), I open sub pages in tabs. Sometimes, this works seemlessly. But more often, I get redirected to /en/dashboard again.
Avoiding to use tabs helps - all pages get loaded as expected.
Note: /en/dashboard is our error fallback, but I've checked remote requests: they were all successful.

**To Reproduce**
1. Go to main page /en/dashboard
2. Open another page in a tab
3. Sometimes, opening the page works as expected - but often not, since the tab starts loading but then gets redirected to /en/dashboard again

**Expected behavior**
Should be irrelevant, if the page is loading in a tab or not.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22, Windows 10
 - Browser Firefox (Ubuntu), Chrome (Win)
 - Version 111.0.1 (64-Bit) (Ubuntu), Chrome version unknown

**Smartphone (please complete the following information):**
 - irrelevant
 
**Additional context**
Our app routings:
`
const routes: Routes = [
  {
    path: '',
    redirectTo: '/dashboard',
    pathMatch: 'full'
  },
  {
    path: 'dashboard',
    loadChildren: () => LandingModule
  },
  {
    path: ':market/dashboard',
    loadChildren: () => LandingModule
  },
  ...errorRoute,
  {
    path: '**',
    redirectTo: '/dashboard'
  }
];

@NgModule({
  imports: [RouterModule.forRoot(routes, {preloadingStrategy: AppCustomPreloader})],
  exports: [RouterModule],
  providers: [AppCustomPreloader]
})
export class AppRoutingModule {}
`

Relevant part of app.module:

`
@NgModule({
  declarations: [AppComponent],
  imports: [
    AppRoutingModule,
    HttpClientModule,
    L10nTranslationModule.forRoot(
      l10nConfig,
      {
        translationLoader: TranslationLoader
      }
    ),
    L10nValidationModule.forRoot(),
    L10nRoutingModule.forRoot()
  ],
  providers: [
    StartupService,
    {
      provide: APP_INITIALIZER,
      useFactory: initL10n,
      deps: [L10nLoader],
      multi: true
    },
  ],
  bootstrap: [AppComponent]
})
export class AppModule {
}
`
(sorry for the formatting)

**Comment by robisim74** [comment] 2023-04-04 21:05
I think this request is a duplicate of #340

**Closed as completed** 2023-05-14 07:56 UTC
Labels: duplicate
