### ISSUE TITLE
Browser language should not win!

### ISSUE THREAD

**Issue by Neill83** [robisim74/angular-l10n#251] opened 2019-06-05 07:43 UTC
**I'm submitting a...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Expected behavior**
Not using browser language before configuration. Browser should **ALWAYS** be the last used config.
**Actual behavior**
browser language wins
**Steps to reproduce the behavior**
[#250](https://github.com/robisim74/angular-l10n/issues/250)

**Comment by robisim74** [comment] 2019-06-05 08:30
@Neill83 this is not a bug, but a defined behavior of this library from the beginning, as in the documentation: https://robisim74.github.io/angular-l10n/spec/configuration/#how-the-language-is-defined-at-the-first-loading

Neither is it necessary to add an option in the configuration settings. If you want to avoid this behavior just set the _defaultLocale_ (even only with the language) instead of the _language_:

```
    locale: {
        languages: [
            { code: 'en', dir: 'ltr' },
            { code: 'it', dir: 'ltr' }
        ],
        defaultLocale: { languageCode: 'en' },
        ...
    },
```
Furthermore, it is always possible to change language after initialization.

Greetings

**Comment by Neill83** [comment] 2019-06-05 08:38
that didn't work for me...

the following helped me to get it working properly
```
storage:       StorageStrategy.Local,
            storageNames:  {defaultLocale: 'my_lang'}
```

**Comment by Neill83** [comment] 2019-06-05 09:22
![image](https://user-images.githubusercontent.com/9987324/58945414-1d637180-8784-11e9-803c-02958a4a3cda.png)
@robisim74 is this relevant? and would you suggest to turn the logging off?

**Comment by robisim74** [comment] 2019-06-05 11:57
This is yet another issue. Please do not confuse the issues so that others can use them as well.

Before opening an issue, please also consult the previous documentation or issues.

[Logger](https://robisim74.github.io/angular-l10n/spec/configuration/#logger) warns you of the most common mistakes: in this case without the implementation of _ngOnInit_ method, the language decorator won't work in prod (see https://robisim74.github.io/angular-l10n/spec/getting-the-translation/#messages)

I'm closing this issue because it's not a bug.

**Closed as completed by robisim74** 2019-06-05 11:57 UTC
Labels: question
