### ISSUE TITLE
String with html is rendering as raw html in Safari 

### ISSUE THREAD

**Issue by smlombardi** [robisim74/angular-l10n#208] opened 2018-09-25 14:58 UTC
**I'm submitting a...**
```
[x ] bug report
[ ] feature request
[ ] support request
```

**Expected behavior**
Our language strings contain html markup, such as `a` tags.  These render correctly as hyperlinks in all browsers but Safari.  Tried Safari 11 and 12 and iOS12.

**Actual behavior**

## In Chrome (also in Firefox and Edge):
<img width="374" alt="rendering in chrome" src="https://user-images.githubusercontent.com/835148/46023182-1e4eea00-c0b2-11e8-998b-ebaa3fa67d2b.png">

## In Safari
<img width="411" alt="rendering in safari" src="https://user-images.githubusercontent.com/835148/46023190-20b14400-c0b2-11e8-8784-b1bd44a2928e.png">

**Steps to reproduce the behavior**

Component code:
```
    <div class="alert alert-danger"
         [innerHTML]="'COOKIES_ALERT'"
         translate></div>
```

String in `en-us.json`:
```
  "COOKIES_ALERT":
    "For your security, this application uses cookies for sign in. You’ll need to enable cookies in your browser’s settings. <a href='https://www.whatismybrowser.com/guides/how-to-enable-cookies/auto' target='_blank'>Learn how</a>"
```

**NOTE** this only happens with l10n translated strings.  Passing the same string directly as a varialble works as expected.

For example, assuming `myVar` is the same string as `COOKIES_ALERT` above:
```
    <div class="alert alert-danger"
         [innerHTML]="myVar"
         translate></div>
```

This works.

**Specifications: Angular version, library version, environment, browser**
```
Angular CLI: 6.0.8
Node: 10.1.0
OS: darwin x64
Angular: undefined
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.8 (cli-only)
@angular-devkit/core         0.6.8 (cli-only)
@angular-devkit/schematics   0.6.8 (cli-only)
@schematics/angular          0.6.8 (cli-only)
@schematics/update           0.6.8 (cli-only)
rxjs                         6.2.2 (cli-only)
typescript                   2.7.2
```

**Comment by robisim74** [comment] 2018-09-25 19:42
Hi @smlombardi,

thanks for reporting, but `innerHtml` is the property binding of Angular for `innerHtml`, a property of HTML Elements: this library does not implement it by itself.

Did you try to insert a link inside `innerHtml `directly without using the library?

**Comment by smlombardi** [comment] 2018-09-25 22:25
Yes, that worked fine with the same string.

**Comment by robisim74** [comment] 2018-09-26 06:50
Could you try these ways?

- Don't use data binding:

`<div class="alert alert-danger" innerHTML="COOKIES_ALERT" translate></div>`

- Use `translate `pipe instead of directive: 

`<div class="alert alert-danger" [innerHTML]="'COOKIES_ALERT' | translate:lang"></div>`

- Use double quotes in the translation:

`"COOKIES_ALERT": "<a href=\"https://www.whatismybrowser.com/guides/how-to-enable-cookies/auto\" target=\"_blank\">Learn how</a>"`

I do not have Safari to test it, so I need your cooperation.

**Comment by smlombardi** [comment] 2018-09-26 19:00
First one:  no difference

second option, gives compile error:
`ERROR in src/app/demo/signin/cookie-alert/cookie-alert.component.html(13,10): : Property 'lang' does not exist on type 'CookieAlertComponent'.`
(I can't find documentation on using the pipe)

third option, no difference.

Interestingly, I have recently found that elsewhere in the application I do NOT have this issue, only in this module's pages.  No errors in the console or compiling though, so I am stumped.

**Comment by robisim74** [comment] 2018-09-26 19:25
To use translate pipe, you have to add _Language_ decorator in the component: https://robisim74.github.io/angular-l10n/spec/getting-the-translation/#messages

With a different html tag (e.g. br), does it work?

**Comment by smlombardi** [comment] 2018-09-26 20:37
Tried a div, p, span

**Comment by robisim74** [comment] 2018-09-26 20:52
So only in that module the texts are translated but html tags are not rendered, and only in Safari. Maybe a conflict with another library used only in that module? Or a particular setting?

**Comment by danielcollettepb** [comment] 2018-10-05 20:33
@robisim74  I was able to get Safari to work using the pure pipe with the language:

![image](https://user-images.githubusercontent.com/6116867/46558495-47922600-c8bb-11e8-8ab1-589d6e0df48e.png)

Here is the HTML for each alert, also tried translate and l10nTranslate directive just to be sure.
```
    <div class="alert alert-danger"
         [innerHTML]="'COOKIES_ALERT' | translate:lang"></div>

    <div class="alert alert-danger"
         [innerHTML]="'COOKIES_ALERT'"
         l10nTranslate></div>

    <div class="alert alert-danger"
         [innerHTML]="'COOKIES_ALERT'"
         translate></div>
```

I tried the suggestion to escape with double quotes and Safari doesn't work.

So we have something that works in Safari, question is why directives don't work and the pipe does...

**Comment by robisim74** [comment] 2018-10-06 10:21
@danielcollettepb 

So, in summary: on Safari, `innerHtml `with pipes works, but not with directives.

The question is: does this always happen or _only in this module_  as said by @smlombardi?

If it happens _only in this module_, I need a repro, otherwise I can't do anything (I can only suggest to use pipes).

**Edit**
See also this question: https://github.com/angular/angular.js/issues/16319 It has been opened in angularjs (but innerHtml is a property of HTML): it could be a Safari bug for innerHtml under certain conditions.

**Comment by danielcollettepb** [comment] 2018-10-06 19:12
I tried another module/component and the directive is still broken in Safari, first alert is the pipe, second directive:

![image](https://user-images.githubusercontent.com/6116867/46574876-acf81c80-c978-11e8-84c5-00a599e9ccab.png)

We were also using `angular-l10n` v5.0.0 and I upgraded to v5.2.0, the issue is still the same in Safari.

We have cases where we pass params into the translation with directives:

```
<p [innerHTML]="'TO_SIGN_IN'"
       translate
       [params]="{url: 'http://reset-password.com'} "></p>
```

I see how to do this in the [pipe documentation](https://robisim74.github.io/angular-l10n/spec/getting-the-translation/#pure-pipes)... if this works in Safari then we have a solution for now.

**Comment by danielcollettepb** [comment] 2018-10-06 19:20
The pipe params work in Safari, directives do not:

![image](https://user-images.githubusercontent.com/6116867/46575005-ecc00380-c97a-11e8-9bb8-a530ed4fa657.png)

```
<p [innerHTML]="'GLOBALIZATION.TO_SIGN_IN' | translate:lang: {url: 'http://reset-password.com'}"></p>

<p [innerHTML]="'GLOBALIZATION.TO_SIGN_IN'"  translate [params]="{url: 'http://reset-password.com'} "></p>
```

So we have a working solution... thanks for the support and a great library. If you need us to test anything out for you, just let us know.

**Comment by robisim74** [comment] 2018-10-06 19:30
Ok.

The point is that directives manipulates the DOM: so I'd need to discover if _innerrHtml_ with directives never work on Safari or only in some case.

**Comment by DavidDon13** [comment] 2018-10-08 15:32
hey there. @robisim74 I'm also having the same issue in safari. innerHtml isn't working for me. Here is my code

` 
<span class="brand" [innerHTML]="'nav.copyright'" translate></span>
`
It gets it's value from a json file:
```
"nav": {
"copyright": "&#169; 2018 Company Name. All rights reserved."
}

```

P.S thanks for this wonderful library!

**Comment by robisim74** [comment] 2018-10-08 16:20
@DavidDon13 Thanks for reporting.

Guys, I need your help. I deployed a new version of the sample app: https://robisim74.github.io/angular-l10n-sample

I added an `innerHTML` using directive here (the title has the `em` tag):

![image](https://user-images.githubusercontent.com/14012361/46620874-47499300-cb26-11e8-82fe-28eeeddbf528.png)

It is correct in Chrome, Firefox, Opera, Edge and IE11. Could you open it with Safari and let me know?

**Comment by DavidDon13** [comment] 2018-10-08 16:34
@robisim74 I just opened sample app on safari my iPhone. It works as expected. I don't notice any innerHTML errors on the page

Will you be deploying a fix for directives in Safari? If not, I can switch to using pipes now. Thanks

**Comment by smlombardi** [comment] 2018-10-08 16:58
The new sample works fine in Safari 12 and Safari 12.1 (tech preview 66) on Mac High Sierra

**Comment by danielcollettepb** [comment] 2018-10-08 17:01
Looks good

![image](https://user-images.githubusercontent.com/6116867/46622989-34b96480-cafa-11e8-811d-e9b4d1a44d26.png)

**Comment by robisim74** [comment] 2018-10-08 18:31
Hi guys, thanks to everyone!

I didn't deploy a fix, I only added an `innerHTML` using directive: so I don't know what's happening in your apps.

Maybe a problem on Safari with multilines or with fixed height of the node or something else like explained in this bug report? https://bugs.webkit.org/show_bug.cgi?id=179922

I understand that it is a boring problem (it is not always possible to try everything in all browsers): but for now I can only recommend using pipes with `innerHTML`.

N.B.
If someone has time to test usign Safari, you should check that the directive gets the key (https://github.com/robisim74/angular-l10n/blob/master/src/models/base-directive.ts#L139) and correctly reassigns it to the `innerHTML `property (https://github.com/robisim74/angular-l10n/blob/master/src/models/base-directive.ts#L100)

**Comment by robisim74** [comment] 2020-02-08 13:42
Closed due to inactivity.

**Closed as completed by robisim74** 2020-02-08 13:42 UTC
Labels: question, need repro
