### ISSUE TITLE
Default language for missing keys

### ISSUE THREAD

**Issue by Deams51** [robisim74/angular-l10n#193] opened 2018-06-07 12:42 UTC
**I'm submitting a...**
```
[ ] bug report
[ ] feature request
[x] support request
```
Is it possible to default to a specific language if a key is missing in another locale?

**Comment by robisim74** [comment] 2018-06-07 14:47
Did you see fallback providers? https://robisim74.github.io/angular-l10n/spec/configuration/#using-fallback-providers

**Comment by Deams51** [comment] 2018-06-07 15:52
Thanks @robisim74 
I did check it out and tried the following configuration:
```
const l10nConfig: L10nConfig = {
  locale: {
    languages: [
      {code: 'en', dir: 'ltr'},
      {code: 'ru', dir: 'ltr'},
      {code: 'zh', dir: 'ltr'},
      {code: 'ko', dir: 'ltr'},
    ],
    language: 'en',
    storage: StorageStrategy.Local
  },
  translation: {
    providers: [
      { type: ProviderType.Fallback, prefix: './assets/locale/locale-', fallbackLanguage: ['en'] },
      { type: ProviderType.Static, prefix: './assets/locale/locale-' }
    ],
    caching: true,
    missingValue: 'No key',
    composedKeySeparator: '.'
  }
};
```

But still getting "No Key" when I remove a key from for example the Korean locale file.

**Comment by robisim74** [comment] 2018-06-07 19:23
@Deams51 Try this:

```
    providers: [
      { type: ProviderType.Fallback, prefix: './assets/locale/locale-en', fallbackLanguage: [] },
      { type: ProviderType.Static, prefix: './assets/locale/locale-' }
    ]
```

That's because `fallbackLanguage` accepts an array of `ISOCode` and not the locale. If the array is empty, the provider service uses the prefix as is.

**Comment by Deams51** [comment] 2018-06-07 22:20
Thank you :) 
Then last question, it seems that if I remove a key in another locale, the fallback works properly, but if the key exists but the string is empty, then _missingValue_ is used even though the key is not empty in the fallback language.
Is it the intended behavior? Shouldn't it look for the value in the fallback language as well? 

Some online translation services will create the locale file with empty strings for missing translations rather than skipping the keys.

**Comment by robisim74** [comment] 2018-06-08 08:18
Yes, that's a behavior by design (not just for fallback). In a logic of key-value, the value is missing only if the key is missing. Otherwise also an empty string is considered a valid value. 

Currently, empty strings are considered voluntary.

**Comment by Deams51** [comment] 2018-06-08 08:26
OK
Would you consider a feature request to add an option to use the fallback in case of an empty string?

**Comment by robisim74** [comment] 2018-06-08 08:41
Yes, PRs are always welcome.

**Comment by robisim74** [comment] 2020-02-08 13:39
Closed via https://github.com/robisim74/angular-l10n/releases/tag/v9.0.0

**Closed as completed by robisim74** 2020-02-08 13:39 UTC
Labels: support request, feature request
