### ISSUE TITLE
Cannot Load translations from Server

### ISSUE THREAD

**Issue by xahanix** [robisim74/angular-l10n#295] opened 2020-04-03 07:32 UTC
Hey there I need some help.

I'm Trying to Load all Translations from Server, but it doesn't work. 

I'm using Angular Version 9.1 and angular-l10n V 9.1.

My l10n-config.ts Look's like this.

```
export const l10nConfig: L10nConfig = {
  format: 'language',
  providers: [
    { name: 'app', asset: environment.apiUrl },
  ],
  fallback: true,
  cache: true,
  keySeparator: '.',
  defaultLocale: { language: 'de-CH', currency: 'CHF' },
  schema: [
    { locale: { language: 'de-CH', currency: 'CHF' }, dir: 'ltr' },
  ],
  defaultRouting: true
};

export function initL10n(l10nLoader: L10nLoader): () => Promise<void> {
  return () => l10nLoader.init();
}

@Injectable() export class HttpTranslationLoader implements L10nTranslationLoader {
  private headers = new HttpHeaders({ 'Content-Type': 'application/json' });

  constructor(
    @Optional() private http: HttpClient,
    private restPath: RestPaths
  ) {

  }

  public get(language: string, provider: L10nProvider): Observable<{ [key: string]: any }> {
    const url = `${provider.asset}${this.restPath.TranslationClient}/de`;
    const options = {
      headers: this.headers,
    };
    return this.http.get(url, options);
  }
}
```
and in my app.module 

```
imports: [
L10nTranslationModule.forRoot(l10nConfig,
      {
        translationLoader: HttpTranslationLoader
      }
)
]

providers: [ 
    {
      provide: APP_INITIALIZER,
      useFactory: initL10n,
      deps: [L10nLoader],
      multi: true
    },
]
```

Then in my component i'm injecting like this

```
  constructor(
    @Inject(L10N_LOCALE) public lang: L10nLocale,
    public locale: L10nIntlService,
    public translation: L10nTranslationService,
  )

```
and using in html

{{ 'FOOTER_COPYRIGHT' | translate:lang.language }}

loaded translation's json look like 

{"de" : {"FOOTER_COPYRIGHT":"Test Project"} }

**Comment by robisim74** [comment] 2020-04-03 07:47
Hi @xahanix,

your code seems correct, but your server should return a json without the language key, as in this example: https://github.com/robisim74/angular-l10n/blob/master/projects/angular-l10n-app/src/assets/i18n/app-en-US.json

**Comment by xahanix** [comment] 2020-04-03 08:08
Hi  @robisim74 
First Thanks a lot for giving that quick response.
Unfortunately, this didn't fix the problem.

The Response look's now like this:
`{"FOOTER_COPYRIGHT": "Test Project", "FOOTER_VERSION":"Version"}`

Could it maybe be a problem with the default language?
Should I set it somewhere additional?

Kind regards

**Comment by robisim74** [comment] 2020-04-03 08:23
Then try to add this to your app component, https://github.com/robisim74/angular-l10n/blob/master/projects/angular-l10n-app/src/app/app.component.ts#L20-L32 and check if translation data and the locale are correct.

**Comment by xahanix** [comment] 2020-04-03 08:28
Locale ist correct set but data is empty

![image](https://user-images.githubusercontent.com/25527030/78340138-d9085400-7595-11ea-9f3f-79081220035d.png)

**Comment by robisim74** [comment] 2020-04-03 08:44
Maybe a problem with the format of the data returned from the server? No error in the network tab or in console? Maybe a caching problem.

Try to change your loader, and load a static json file: the logic is the same.

**Comment by xahanix** [comment] 2020-04-03 09:36
No error in the Network tab. And also not working with a static file.

JSON File looks like:

```
{
  "FOOTER_COPYRIGHT": "App",
  "FOOTER_VERSION": "Version",
  "FOOTER_HOTLINE": "Hotline"
}
```

And Method:

```
@Injectable() export class HttpTranslationLoader implements L10nTranslationLoader {
  private headers = new HttpHeaders({ 'Content-Type': 'application/json' });

  constructor(
    @Optional() private http: HttpClient,
    private restPath: RestPaths
  ) {
  }

  public get(language: string, provider: L10nProvider): Observable<{ [key: string]: any }> {
    const url = `${provider.asset}.json`;
    const options = {
      headers: this.headers,
    };
    return this.http.get(url, options);
  }
}
```


Interesting Behaviour: None of the keys is translated due to the pipe in the first load, but when I execute a Code piece that call's 

`this.localization.translate('FOOTER_VERSION')`

It's working.

Maybe good to know. I'm loading pages/components with lazy loading.

**Comment by robisim74** [comment] 2020-04-03 11:30
Weird. If the problem is not limited, I need a repro.

Also here you can find an example app complete with lazy loading: https://github.com/robisim74/angular-l10n/tree/master/projects/angular-l10n-app

**Comment by thomae82** [comment] 2020-04-07 06:30
I am further investiganting this issue reported from @xahanix and I can see that the request is executed but the value is not loaded into this.translation.data.
When I force a reload everything works. It seems to be the initial request that is failing :-/

![image](https://user-images.githubusercontent.com/14110679/78637134-1298d200-78aa-11ea-994c-9197a8fa4d9a.png)

**Comment by robisim74** [comment] 2020-04-07 08:18
Are you colleagues?  I've already explained that I can't understand what's going on in your app without a repro.

**Comment by nickroberts** [comment] 2020-04-11 00:00
I am getting a weird error, as well, when lazy loading translations from a project created with [nx](https://nx.dev/angular).

```
core.js:6189
ERROR Error: Uncaught (in promise): angular-l10n (formatLanguage): Invalid language
    at resolvePromise (zone-evergreen.js:798)
    at resolvePromise (zone-evergreen.js:750)
    at zone-evergreen.js:860
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:41442)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
    at Zone.runTask (zone-evergreen.js:167)
    at drainMicroTaskQueue (zone-evergreen.js:569)
```

What's weird, is that it works fine with the exact same code when I just create a project with the [Angular CLI](https://github.com/angular/angular-cli).

* [Repo for the ng version](https://github.com/nickroberts/test-angular-l10n)
* [StackBlitz project for the ng version](https://stackblitz.com/edit/test-angular-l10n)
* [Repo for the nx version](https://github.com/nickroberts/test-angular-l10n-nx)
* [(non-functioning) StackBlitz project for the nx version](https://stackblitz.com/edit/test-angular-l10n-nx)

Looks like there might be some issues with running an Nx project in StackBlitz. [Here is a pristine project that was generated with nx on StackBlitz](https://stackblitz.com/edit/stackblitz-nx-test).

If this can't be figured out, I'm going to move away from using Nx. I like it, but I think I can get most of what I want done with just the Angular CLI (multiple projects / libraries).

**Comment by nickroberts** [comment] 2020-04-11 00:07
My comment might be on the wrong issue, or it could be its own. Sorry, if that's the case!

Also, the loading works fine if you are in the app, but if you refresh the page that is lazy loaded (/lazy, in my case), then you get that error.

**Comment by robisim74** [comment] 2020-04-11 12:58
@nickroberts I moved your request to a new issue (#301). I will try to investigate.

**Comment by robisim74** [comment] 2020-04-11 13:01
@xahanix I'm closing for lack of repro. If you need, open a new issue with the specific problem and reproduction.

**Closed as completed by robisim74** 2020-04-11 13:01 UTC
Labels: question, need repro
