### ISSUE TITLE
localeValidation.parseNumber return NaN for hr locale on internet explorer 11

### ISSUE THREAD

**Issue by moromete** [robisim74/angular-l10n#272] opened 2019-11-28 12:34 UTC
[x ] bug report
[ ] feature request
[ ] support request

**Expected behavior**
this.localeValidation.parseNumber('1,123', '1.0-6', 'hr');
must return 1.123
decimalSeparator should be ','
thousandSeparator should be '.'

**Actual behavior**
this.localeValidation.parseNumber('1,123', '1.0-6', 'hr');
return NaN
decimalSeparator is detected as '0'
decimalSeparator is detected as '1'

**Steps to reproduce the behavior**
Ie 11 new Intl.NumberFormat('hr').format(-1000.9) return - 1.000,9 instead of -1.000,9 adding an extra space after minus sign.
so function  getDecimalCode is reading the decimal character from the wrong position because the string is one char longer.

**Specifications: Angular version, library version, environment, browser**
angular-l10n 8.2.13
ie 11.1.19025.0

**Comment by robisim74** [comment] 2019-11-28 20:02
Hi @moromete,
If the problem is only with IE, it is a IE bug.
As a workaround, you could pass another locale when you call the method when your locale is _hr_, like _it_ which has the same decimal and thousand separator.

**Comment by robisim74** [comment] 2020-02-08 13:56
Closed via https://github.com/robisim74/angular-l10n/releases/tag/v9.0.0

**Closed as completed by robisim74** 2020-02-08 13:56 UTC
Labels: question
