### ISSUE TITLE
TranslationService.translate() to specific language not working

### ISSUE THREAD

**Issue by mscudlik** [robisim74/angular-l10n#271] opened 2019-11-22 16:11 UTC
Hi Roberto,

first of all thanks a lot for providing this great library, it works very well.

I currently have a small issue with version *8.1.2*:
- the app supports 2 languages
- both languages are passed inline as json in the  i18n-config

I have a specific situation where i want to always use the english text - which is why i use the following statement:

```typescript
let myKey = 'foo.bar'
this.translationService.translate(myKey, '', 'en');
```

This works when the language is en, but not in other cases.

The reason seems to be in getValue() of TranslationService:

https://github.com/robisim74/angular-l10n/blob/v8.1.2/src/services/translation.service.ts#L190

Here this.translationData only contains the currently active language, so that nothig is found for the non active language. Even though the i18n config contains both languages:

```typescript
export const l10nConfig: L10nConfig = {
  locale: {
    languages: [
      { code: 'en', dir: 'ltr' },
      { code: 'de', dir: 'ltr' }
    ],
    language: 'en', // fallback language
    storage: StorageStrategy.Local
  },
  translation: {
    translationData: [
      { languageCode: 'en', data: TRANSLATION_EN },
      { languageCode: 'de', data: TRANSLATION_DE }
    ],
    caching: true,
    composedKeySeparator: '.' // this is required (!)
  }
};
```

TRANSLATION_EN and DE contain the complete translation.

Is this a bug or am i doing something wrong?

Thanks and best regards,
Matthias

**Comment by robisim74** [comment] 2019-11-22 16:28
Hi Matthias,

it's not a bug and you are not doing anything wrong. _this.translationData only contains the currently active language_: yes, it was by design, to improve performance.

In the next version (v9) all languages are added (but only if they are required), and however there is the possibility to access the translation data and preload them.

**Comment by mscudlik** [comment] 2019-11-23 13:38
Hi Roberto,

can you explain how to preload the translation data without actually changing the current language in v8?

I only found:

loadTranslation(): Promise<any> | Forces the translation loading for the current language.

Which seems to only work when i change the language.

Thanks and best regards,
Matthias

**Comment by robisim74** [comment] 2019-11-24 10:02
As I said, it is not possible with v8.

**Comment by robisim74** [comment] 2020-02-08 13:56
Closed via https://github.com/robisim74/angular-l10n/releases/tag/v9.0.0

**Closed as completed by robisim74** 2020-02-08 13:56 UTC
Labels: question
